#!/bin/sh

# . /etc/openwrt_release
# echo "src/gz piratebox http://stable.openwrt.piratebox.de/$DISTRIB_TARGET/packages" >> /etc/opkg.conf

[ -f "$IPKG_INSTROOT/etc/opkg.conf" ] &&
  grep '[ \t]*src/gz[ \t]*piratebox[ \t]*' "$IPKG_INSTROOT/etc/opkg.conf" > /dev/null &&
  exit 0

echo "src/gz piratebox http://stable.openwrt.piratebox.de/all/packages" >> "$IPKG_INSTROOT/etc/opkg.conf"
